services:
  mailhog:
    image: mailhog/mailhog
    container_name: 'sistema_moedas_mailhog'
    ports:
      - "${SPRING_MAIL_PORT}:1025"
      - "8025:8025"
    networks:
      - sysvantagens-network

  sistema-moedas:
    build: .
    container_name: 'sistema_moedas'
    restart: always
    ports:
      - "${SPRING_PORT}:8080"
    env_file:
      - ./.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${SPRING_DATASOURCE_DBNAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_MAIL_HOST=mailhog
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
    depends_on:
      - db
      - mailhog
    networks:
      - sysvantagens-network

  db:
    image: postgres:13
    container_name: sysvantagens_db
    restart: always
    expose:
      - "5432"
    ports:
      - "${SPRING_DATASOURCE_PORT}:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${SPRING_DATASOURCE_DBNAME}
    networks:
      - sysvantagens-network

networks:
  sysvantagens-network:
    driver: bridge